global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'payu-services'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: 
        - 'host.docker.internal:8001' # account-service
        - 'host.docker.internal:8002' # auth-service
        - 'host.docker.internal:8003' # transaction-service
        - 'host.docker.internal:8004' # wallet-service
