quarkus:
  application:
    name: backoffice-service
  http:
    port: 8099
    test-port: 0
  otel:
    service:
      name: backoffice-service
    exporter:
      otlp:
        endpoint: ${OTEL_ENDPOINT:http://localhost:4317}
    resource:
      attributes:
        - service.name=backoffice-service
        - service.version=1.0.0
  datasource:
    db-kind: postgresql
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    jdbc:
      url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
  hibernate-orm:
    database:
      generation: none
    physical-naming-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    sql-load-script: no-file
  flyway:
    migrate-at-start: true
    validate-on-migrate: true
    baseline-on-migrate: true
  log:
    category:
      "id.payu.backoffice":
        level: INFO
"%test":
  quarkus:
    datasource:
      jdbc:
        url:
    flyway:
      migrate-at-start: true
